get:
  tags: [Leave]
  summary: Get user leave applications
  operationId: getLeaveApplications
  responses:
    '200':
      description: User leave applications
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/leave-response.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../components/common/error-response.yaml
