name: Deploy Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, app1]

    concurrency:
      group: deploy-dev
      cancel-in-progress: true

    steps:

      - name: Deploy app
        run: |
          cd /home/deploy/saher/saher-backend
          git pull origin dev
          cd /home/deploy/saher
          docker compose up -d --build

      - name: Verify containers
        run: docker ps
